### ISSUE TITLE
inactive nozzle is not cooled down

### ISSUE THREAD

**Issue by khumarahn** [fughilli/multimaterial-cura-postprocess#1]
Hi, I tried this script with Cura 4.1 on the poker chip from thingiverse. 

Something is not right, because it just keeps both nozzles hot all the time.
Here is a link to my nextcloud folder with all files:
https://khu.dedyn.io/cloud/index.php/s/Eb3AsQdyCCLiBJr

Also, to make the program run, I had to change
```
index 2bb2fb2..767c026 100644
--- a/postprocess_lib.py
+++ b/postprocess_lib.py
@@ -82,7 +82,7 @@ def rewrite(gcode_string, op_regex, override={}, force={}, delete=[]):
         return gcode_string
 
     for k, v in override.items():
-        if args_dict.has_key(k):
+        if k in args_dict:
             args_dict[k] = v
 
     for k, v in force.items():
@@ -166,7 +166,7 @@ class TempProcessor(Processor):
         return True
 
     def update_idle_temps(self, extruder, temperature):
-        if not self.idle_temps.has_key(extruder):
+        if extruder not in self.idle_temps:
             self.idle_temps[extruder] = temperature
             return
 
@@ -176,7 +176,7 @@ class TempProcessor(Processor):
         return
 
     def update_printing_temps(self, extruder, temperature):
-        if not self.printing_temps.has_key(extruder):
+        if extruder not in self.printing_temps:
             self.printing_temps[extruder] = temperature
             return
 
```

**Comment by fughilli** [comment]
Ack! This is because the script doesn't observe the tool changes in the file, and therefore doesn't insert the temperature ramp down sequence. I forgot to add instructions for configuring Cura. I updated the README with instructions. Give those a shot and let me know if it works for you!

**Comment by fughilli** [comment]
I think your issue with the `has_key` method is because I wrote the script for python2. The `in` keyword approach is supported in both versions, so I'll accept a pull if you send one.

**Comment by khumarahn** [comment]
Hi. I added the lines as in README. Still cannot make it work. It now cools both nozzles at the same time, or heats both at the same time, with something inexplainable in between. I added files to the folder, this time it is `lorenz*.gcode`.

I don't think that changing `has_key` to `in` is worth a PR :-)
